In [1]:
#Creating a vector
import numpy as np

vector = np.array([[1,1,1],[1,3,3]])

In [2]:
#Creating matrix
print(np.mat(vector))
matrix = np.mat([[1,2,3],[2,34,4],[3,2,3]])
print(matrix)

[[1 1 1]
 [1 3 3]]
[[ 1  2  3]
 [ 2 34  4]
 [ 3  2  3]]


In [3]:
#Creating Sparse Matrix
#Sparse : Small in qty. i.e reducing the size of matrix if the matrix contains few zeroes
from scipy import sparse
a = np.array([[0,1],[2,0],[2,3]])
a_sparse = sparse.csr_matrix(a)
#csr - compressed sparse row 
#This is useful when we have have large matrix with lots of cells having 
#CSR gives the indices of the non-zero values and index starts from zero

In [4]:
print(a)
print(a_sparse)

[[0 1]
 [2 0]
 [2 3]]
  (0, 1)	1
  (1, 0)	2
  (2, 0)	2
  (2, 1)	3


In [5]:
#Selecting a element or elements from  vectors and matrix

vector = np.array([1,3,3,5])
matrix = np.mat([[1,3,2],[2,3,5],[5,6,4]])

#Selecting an element
print(vector[0])
print(matrix[0,1])
#Index starts from zero for numpy

#Selecting all elements of a vector
vector[:] # or just vector

matrix[:,:] # or just matrix

print(vector[-1]) #Selecting last element

matrix[:2] #Gives rows
matrix[:1,:2]#Gives upto first row and upto 2nd column

1
3
5


matrix([[1, 3]])

In [6]:
#Describing a Matrix\

matrix.shape # Shape of matrix

matrix.size # rows*columns

np.mat([[1,2],[1,3],[2,4],[5,3]]).ndim # number of dimensions
#matrix is always 2-dimension

2

In [7]:
# Applying operations to elements
a = np.array([[2,3,4],[2,3,2]])
into = lambda i : i*10
into(a) #also possible to matrix
a*100 #This also possible

array([[200, 300, 400],
       [200, 300, 200]])

In [8]:
#Maximum and Minimum
print(np.max(a)) # Maximum of whole matrix

print(np.min(a)) # Minimum of whole matrix

print(np.max(a,axis=0))# Max in each column

print(np.max(a,axis=1))#Max in each row

4
2
[2 3 4]
[4 3]


In [9]:
# Average, Variance and Std deviation
print(np.mean(a)) #Average

print(np.var(a)) #Variance

print(np.std(a)) #Std Deviation 
#Here also axis can be used to descriptive statistics for respective rows and columns

2.6666666666666665
0.5555555555555555
0.7453559924999298


In [10]:
# Reshaping Arrays
#Changing the shape of the array without changing the element values
print(a.shape)

print(a.reshape(3,2))
print(a.reshape(1,6))

print(a.reshape(-1,1)) #Gives only one col and as many rows as possible 
print(a.reshape(1,-1)) #Gives only one row and as many cols as possible

print(a.reshape(6)) #Gives 1D array

(2, 3)
[[2 3]
 [4 2]
 [3 2]]
[[2 3 4 2 3 2]]
[[2]
 [3]
 [4]
 [2]
 [3]
 [2]]
[[2 3 4 2 3 2]]
[2 3 4 2 3 2]


In [11]:
#Transposing a Vector or a Matrix
print(a)
print(a.T) #Transpose of matrix a

print(np.array([1,1,2]).T)
#transpose of a vector is itself

[[2 3 4]
 [2 3 2]]
[[2 2]
 [3 3]
 [4 2]]
[1 1 2]


In [12]:
# Flattening a matrix or converting matrix into 1D array

print(a)
print(a.flatten()) #Reshape can be used
print(a.reshape(1,-1))

[[2 3 4]
 [2 3 2]]
[2 3 4 2 3 2]
[[2 3 4 2 3 2]]


In [13]:
# Rank of a Matrix
print(a)

np.linalg.matrix_rank(a) # Rank of a matrix is the dimension of vector space spanned by its columns or rows

[[2 3 4]
 [2 3 2]]


2

In [14]:
# Determinant of Matrix
b = np.array([[1,2],[3,5]])
print(b)
np.linalg.det(b)

[[1 2]
 [3 5]]


-1.0000000000000004

In [15]:
#Diagonal of a Matrix
c = np.array([[1,2,3,5],[5,6,3,6],[2,9,0,7],[2,3,2,1]])
print(c)
print(c.diagonal())

#To get diagonal off from main  diagonal
print(c.diagonal(offset=1))
print(c.diagonal(offset=-2))

[[1 2 3 5]
 [5 6 3 6]
 [2 9 0 7]
 [2 3 2 1]]
[1 6 0 1]
[2 3 7]
[2 3]


In [16]:
#Trace of the Matrix
#Trace is the sum of the diagonal elements
print(b)
sum(b.diagonal())

[[1 2]
 [3 5]]


6

In [17]:
# Eigenvalues and Eigenvectors
# eigenvectors are vectors that, when that transformation is applied, change only in scale (not direction)
# A*v = X*v
#Where A is sqr matrix and X contains eigenvalues and v contains eigenvectors

print(c)
eigen_vals, eigen_vectors = np.linalg.eig(c)
print("Eigenvalues : ",eigen_vals)
print("Eigenvecors :", eigen_vectors )

[[1 2 3 5]
 [5 6 3 6]
 [2 9 0 7]
 [2 3 2 1]]
Eigenvalues :  [14.17660527+0.j         -1.63256218+1.84165369j -1.63256218-1.84165369j
 -2.91148091+0.j        ]
Eigenvecors : [[ 0.34836547+0.j         -0.52682779-0.31799417j -0.52682779+0.31799417j
   0.16773208+0.j        ]
 [ 0.65104012+0.j          0.0113721 +0.33838646j  0.0113721 -0.33838646j
  -0.08907863+0.j        ]
 [ 0.60727014+0.j          0.69267901+0.j          0.69267901-0.j
  -0.88111732+0.j        ]
 [ 0.29327672+0.j         -0.02564784-0.16197357j -0.02564784+0.16197357j
   0.43308568+0.j        ]]


In [18]:
# Dot Product
print(b)
e = b-2
print(e)

print(np.dot(e,b))
print(e@b) 

[[1 2]
 [3 5]]
[[-1  0]
 [ 1  3]]
[[-1 -2]
 [10 17]]
[[-1 -2]
 [10 17]]


In [19]:
#Addition and Subtraction

print(e+b)
print(np.add(e,b))

print(e-b)
print(np.subtract(e,b))

[[0 2]
 [4 8]]
[[0 2]
 [4 8]]
[[-2 -2]
 [-2 -2]]
[[-2 -2]
 [-2 -2]]


In [20]:
#Multiplication 

print(e)
print(b)
print(e@b)

print(e*b) #Elementwise multiplication

[[-1  0]
 [ 1  3]]
[[1 2]
 [3 5]]
[[-1 -2]
 [10 17]]
[[-1  0]
 [ 3 15]]


In [21]:
#Inverting a Matrix
print(e)
print(np.linalg.inv(e))

a = np.array([[1,0],[1,0]])
print(a)
print(np.linalg.inv(a))


[[-1  0]
 [ 1  3]]
[[-1.         -0.        ]
 [ 0.33333333  0.33333333]]
[[1 0]
 [1 0]]


LinAlgError: Singular matrix

In [22]:
# Generating Random values
#set.seed()
np.random.seed(1)

np.random.random(3) # Random floats between 0 and 1

#Random integers from 0 to 20
np.random.randint(0,21,3) # (min,max+1,n)

array([11,  5, 15])

In [23]:
#Random normal values
np.random.normal(0,2,5) #(mean,sd,n)

array([-1.09949235, -2.80574543,  3.1655046 , -2.09029366,  0.51518703])

In [24]:
#Random uniform values
np.random.uniform(-5,5,8) #(min,max,n)

array([-0.56547106, -2.70422786,  0.34413909,  4.13962025, -0.42795192,
       -0.69301433,  4.39127789,  2.78389236])

In [25]:
#Random logistic values
np.random.logistic(0,3,5) #(mean,sd,n)

array([ 2.77368281,  4.21085629, -6.83972006,  0.21792637,  5.5728845 ])

In [26]:
#Random Exponential values
np.random.exponential(5,6) # (lambda,5)

array([8.834756  , 8.8481319 , 1.59448772, 0.30535311, 5.55132014,
       4.49551543])

In [27]:
#Random Binomial values
np.random.binomial(10,0.5,5) #(n,p,no of obs)

array([6, 5, 4, 4, 3])

In [28]:
#Random Poisson values
np.random.poisson(10,8) #(mean,n)

array([13, 12,  9,  4,  5,  5, 15, 11])